### ISSUE TITLE
Cannot checkout project branch

### ISSUE THREAD

**Issue by sabinbajracharya** [UniversityOfAppliedSciencesFrankfurt/se-cloud-2020-2021#118]
**sabin@Sabins-MacBook-Pro se-cloud-2020-2021 %** git checkout ML2021-5.4-Investigate-stability-of-Homeostatic-Plasticity-Controller-By-Team-Aspire

Downloading MyProject/Documentation/Video.mp4 (78 MB)

**Error downloading object:** MyProject/Documentation/Video.mp4 (9c96632): Smudge error: Error downloading MyProject/Documentation/Video.mp4 (9c9663258e885e7298123b9beb2ec80b8bd4c9d26bb4ae35cb64cef23f94a3cd): batch response: **This repository is over its data quota**. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /Users/sabin/Documents/university/se-cloud-lab/se-cloud-2020-2021/.git/lfs/logs/20210628T113536.706436.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: MyProject/Documentation/Video.mp4: smudge filter lfs failed

**Comment by sabinbajracharya** [comment]
@ddobric  For now I've deleted the Software Engineering Presentation video and was able to switch to the branch.

**Comment by ddobric** [comment]
@PRnnr ?
